micronaut:
  application:
    name: micronaut-crud
datasources:
  default:
    url: jdbc:mysql:////localhost:3306/mn_playground
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
flyway:
  datasources:
    default:
      enabled: true